const mongoose = require('mongoose');
const FormDataSchema = new mongoose.Schema({
    name: String,
    dateOfBirth: Date,
    gender: String,
    contactNo: String,
    email: String,
    religion: String,
    institutionName: String,
    state: String,
    course: String,
    year: String,
    enrollmentNo: String,
    xthPercentage: String,
    xiithPercentage: String,
    ugPercentage: String,
    address: String,
    homeState: String,
    reasonOfLeavingState: String,
    scholarshipName: String,
    reasonForDenyingScholarship: String,
    disabilities: String,
    disabilityDetails: String,
    disabilityCertificate: String,
    xthMarksheet: String,
    xiithMarksheet: String,
    ugCertificate: String,
    pgCertificate: String,
    birthCertificate: String,
    communityCertificate: String,
    aadharCard: String,
    idCard: String,
    feeReceipt: String
});

module.exports = mongoose.model('FormData', FormDataSchema);
